spring:
  application:
    name: bookManagement

  datasource:
    url: jdbc:postgresql://postgres:5432/appdb
    username: appuser
    password: apppass
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  jooq:
    sql-dialect: POSTGRES

  docker:
    compose:
      enabled: false   # ? ??????docker????????????

server:
  port: 8080
